### ISSUE TITLE
Failed to read portal settings

### ISSUE THREAD

**Issue by pnemade** [flathub/org.gnome.gedit#10]
On Fedora 29 Workstation, running this gedit flatpak, I am getting below debug messages
(gedit:2): Gdk-WARNING **: 12:01:35.912: Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop

(gedit:2): Gtk-WARNING **: 12:01:36.110: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

Can these be fixed? I think the first message is common to other Gnome applications as well e.g, evince.

**Comment by TingPing** [comment]
Neither are a problem with the app.
