### ISSUE TITLE
Info on flathub site is missing 

### ISSUE THREAD

**Issue by yodatak** [flathub/org.gnome.gedit#14]
On flathub it lack the version , i don't know how to change it ( it could be could to know if gedit is on gnome 3.32 directly on flathub and not in json file ) :)
```

Updated
-
Version
-
Developer
-
```

**Comment by TingPing** [comment]
The version/release date information belongs upstream: https://gitlab.gnome.org/GNOME/gedit/issues

**Comment by jbicha** [comment]
Upstream gedit needs to add release info to its AppStream metadata for the version to show up with Flatpak. I am closing this issue here because this can't be fixed in the Flathub metadata.
