### ISSUE TITLE
Not found by gnome shell

### ISSUE THREAD

**Issue by akurtakov** [flathub/org.gnome.gedit#15]
Latest gedit installed from flathub.
Steps to reproduce:

Super key
Type gedit
no gedit shown thus not launchable

but 'flatpak run org.gnome.gedit' works just fine.

**Comment by t-chaik** [comment]
Should have been fixed by [!44](https://gitlab.gnome.org/GNOME/gedit/merge_requests/44) and will be shipped in next version (3.34.0).
