### ISSUE TITLE
Font Resizing Plugin is Missing

### ISSUE THREAD

**Issue by alex285** [flathub/org.gnome.gedit#2]
is there any way to install it on Flatpak build?

**Comment by nedrichards** [comment]
It'd need to be packaged separately as an extension

**Comment by t-chaik** [comment]
Plugins (from `gedit-plugins`) are now ship by default (since at least `org.gnome.gedit//3.32.0`).

Would you mind testing again?

**Comment by alex285** [comment]
sorry for the late response, yeap works! thank you!
