### ISSUE TITLE
Become maintainer

### ISSUE THREAD

**Issue by swilmet** [flathub/org.gnome.gedit#23]
I'm the upstream maintainer of gedit, see the [gedit doap file](https://gitlab.gnome.org/GNOME/gedit/-/blob/master/gedit.doap), and I would like to maintain the Flatpak on Flathub.

I'm already a maintainer of a Flatpak on Flathub, for: https://github.com/flathub/org.gnome.Devhelp

**Comment by swilmet** [comment]
@bilelmoussaoui : I see that you have pushed some commits in this repo, can you add me as maintainer for the gedit flatpak?

**Comment by bilelmoussaoui** [comment]
Invitation sent

**Comment by swilmet** [comment]
Cool, thanks! :+1:
