### ISSUE TITLE
Gedit is missing the "Text Editor" printing tab

### ISSUE THREAD

**Issue by njam** [flathub/org.gnome.gedit#33]
According to articles on the Internet Gedit has a "Text Editor" tab in the printing settings, that allows to configure how text files are styled for printing (e.g. [AskUbuntu](https://askubuntu.com/questions/237336/how-to-hide-filepath-and-page-number-in-gedit-for-printing)).

I can't see this "Text Editor" tab in my flatpak Gedit.
It's just a guess, but is it possible that the flatpak version doesn't have this tab?

<img src=https://user-images.githubusercontent.com/360800/146611982-672bc188-ea08-43a0-998a-f9dd232b6aaf.png height=300>

**Comment by TingPing** [comment]
Customizing print behavior isn't doable through the Flatpak printing portal.
